name: motrainer
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab # needed to run notebooks
  - numpy
  - scipy
  - tensorflow
  - scikit-learn
  - pandas <= 2.0.0
  - scikit-optimize
  - ipykernel
  - matplotlib
  - pip
  - xarray
  - pip:
    - -e ./
