name: Build

on: [push, pull_request]

jobs:

  build:
    name: Build for ${{ matrix.python-version }}
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6', '3.7', '3.8']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Python info
        shell: bash -l {0}
        run: |
          which python
          python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build
        shell: bash -l {0}
        run: |
          python setup.py build
      - name: Test
        shell: bash -l {0}
        run: |
          pip install pytest pytest-cov pycodestyle
          pytest --cov --cov-report term --cov-report xml --junitxml=xunit-result.xml
